development:
  adapter: postgresql
  encoding: unicode
  database: ping_pong_development
  #database: ace_ping_pong_backup_05_10
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: ping_pong_test
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: ping_pong_production
  host: localhost
  pool: 5
